### ISSUE TITLE
Nil

### ISSUE THREAD

**Issue by StellaLulu** [shinke-li/Campus3D#2]

**Comment by stellactyy** [comment]
## Conclusion of Campus3D

The algorithm cannot be run in Razer because it requires Linux and > 16GB RAM to run. Also there are outdated libraries in pointnet2 and Dockerfile.

Required RAM : 32 GB (out of memory error for 16GB)                                
Python version: 3.7.3 (but there is python2 syntax in the script)                                
CUDA version: 10.0                                
OS: Linux (requires actual GPU)          

Tested with Ubuntu in WSL however it doesn't support nvidia-container-toolkit. Some libraries can only be installed in independent Linux environment.      

Besides, the script has to be modified to run given that there are both Python2 (from pointnet2) and Python 3 syntax, also outdated libraries.     

### Docker                           
`Dockerfile` in the repo will give compile error due to outdated `.deb` file, to run it the script has to be modified to...

    FROM shinkeli/conda-tf2-open3d:v1

    MAINTAINER shinkeli

    RUN apt update && apt install -y libgl1-mesa-glx

`nvidia-container-toolkit` can only be installed in Linux

### Package	Version
| Package        | Version    |Version    |
| ------------- |:-------------:|------------- |
| numpy	 | 1.16.6 | 
| numba | 0.47.0 | 
| open3d | 0.9.0.0 | 
| pyyaml | 5.1.2 | 
| sparse | 0.6.0 | 
| h5py | 2.10.0 | 
| torch | 1.0.0 |             
| faiss-gpu | 1.6.3  | Only support MacOS / Linux |    
| tensorflow-gpu | 1.13.1 |
